### PR TITLE
OAuth to Pleroma fails due to URL-only parameters

### PR DESCRIPTION
**Pull request by rjp**
Calling `madonctl -i pleroma-instance oauth2 get-url` results in:
```
Error: app registration failed: API query (v1/apps) failed: bad server status code (400): Missing field: client_name. Missing field: redirect_uris.
```
because whatever Pleroma is using for handling OAuth / HTTP won't parse out parameters from the URL on a `POST` request (which is fair -- the HTML 5 specs advises that `POST`s should have the URL encoded parameters in the body, not the URL.)

Fixes madonctl:#27

### CODE REVIEW

**Comment by McKael** [comment]
Also, this patch might add a trailing `?` to the GET URLs when there are no query params (not a big deal though...). :smile:

**Comment by rjp** [comment]
I'll have another look this week and see if it can be made more robust.

**Comment by rjp** [comment]
Apologies for the delay.  I see what you mean with `UploadMediaReader` and `UpdateAccount`.  I think they can probably be rejigged to pass the file in as a parameter which avoids the issue but I'll have a deeper look - that would solve the issue satisfactorily, no?

**Comment by rjp** [comment]
This makes media uploads create their own `req.Body` and `restAPI()` will respect that by not overwriting it.  Also removes the dangling `?` if there's no parameters.  Have tested media upload with my GotoSocial, my Akkoma, and whatever version of Mastodon Octodon is running.  All works fine.

**Comment by McKael** [comment]
Thanks for the update @rjp, this looks good.

And I really apologize for the lack of responsiveness.  Time flies! :-/

**Pull request merged**
